=== leonbornemann/XML-Project/resources/XMLSchema QuestionsToClient/questionsToClient.xsd
<?xml version="1.0" encoding="UTF-16"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation xml:lang="EN">
			question-schema for XML-project 2015
			Copyright 2015 all rights reserved.
		</xsd:documentation>
	</xsd:annotation>


	<xsd:element name="languageExamples" type="languageExamplesType"/>

	<xsd:complexType name="languageExamplesType">
		<xsd:sequence>
			<!-- TODO: Set minOccurs to X; X is the number of questions in XML document -->
			<xsd:element name="example" type="exampleType" minOccurs="2" maxOccurs="10"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="exampleType">
		<xsd:sequence>
			<xsd:element name="sentence" type="sentenceType"/>
			<xsd:element name="answers" type="answersType"/>

			<xsd:element name="officialLanguageOf" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="sentenceType">
		<xsd:sequence>
			<xsd:element name="original" type="xsd:string"/>
			<xsd:element name="english" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="answersType">
		<xsd:sequence>
			<xsd:element name="correct" type="xsd:string"/>
			<xsd:element name="wrong" type="xsd:string" minOccurs="3" maxOccurs="3"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== leonbornemann/XML-Project/resources/XMLSchema QuestionsToClient/questionsToClientExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<languageExamples xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="questionsToClient.xsd">
	<!-- send all necessary information -->
	<example>
		<sentence>
			<original>
			Peter wusch die Füße seines Sohns.
			</original>
			<english>
			Paul washed his son’s feet.
			</english>
		</sentence>
		<answers>
			<correct>
			German
			</correct>
			<wrong>
			English
			</wrong>
			<wrong>
			Finnish
			</wrong>
			<wrong>
			Polish
			</wrong>
		</answers>

		<!-- extra information -->
		<officialLanguageOf>
		Germany
		</officialLanguageOf>
		<officialLanguageOf>
		Liechtenstein
		</officialLanguageOf>
	</example>
	<example>
		<sentence>
			<original>
			Peter wusch die Füße seines Sohns.
			</original>
			<english>
			Paul washed his son’s feet.
			</english>
		</sentence>
		<answers>
			<correct>
			German
			</correct>
			<wrong>
			English
			</wrong>
			<wrong>
			Finnish
			</wrong>
			<wrong>
			Polish
			</wrong>
		</answers>

		<!-- extra information -->
		<officialLanguageOf>
		Germany
		</officialLanguageOf>
		<officialLanguageOf>
		Liechtenstein
		</officialLanguageOf>
	</example>
</languageExamples>
