=== leonbornemann/XML-Project/resources/XMLSchema DataRepresentation/dataRepresentation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation xml:lang="EN">
			data-representation-schema for XML-project 2015
			Copyright 2015 all rights reserved.
		</xsd:documentation>
	</xsd:annotation>

	<xsd:element name="languageExamples" type="languageExamplesType"/>

	<xsd:complexType name="languageExamplesType">
		<xsd:sequence>
			<xsd:element name="languageExample" type="languageExampleType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="languageExampleType">
		<xsd:sequence>
			<xsd:element name="example" type="exampleType" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="language" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="exampleType">
		<xsd:sequence>
			<xsd:element name="original" type="xsd:string"/>
			<xsd:element name="translation" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== leonbornemann/XML-Project/resources/XMLSchema DataRepresentation/dataRepresentationExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<languageExamples xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="dataRepresentation.xsd">
	<languageExample language="German">
		<example>
			<original>
			Hallo
			</original>
			<translation>
			Hello
			</translation>
		</example>
		<example>
			<original>
			Baum
			</original>
			<translation>
			Tree
			</translation>
		</example>
	</languageExample>
	
<languageExample language="Finnish">
		<example>
			<original>
			Mit√§; kuuluu?
			</original>
			<translation>
			How are you?
			</translation>
		</example>
		<example>
			<original>
			puu
			</original>
			<translation>
			Tree
			</translation>
		</example>
	</languageExample>
</languageExamples>
